name: Swoogo Autodeploy
on:
  push:
    branches: [ main ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Stats
        run: |
          env
      - name: Docker Loggin
        run: |
          echo ${{ secrets.REPOSITORY_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Run
        run: |
          docker container run --rm -v "/home/runner/work/test-autodeploy/test-autodeploy:/repositories/project" -e USER_USERNAME=${{ vars.USER_USERNAME }} -e USER_PASSWORD=${{ vars.USER_PASSWORD }} -e ROOT_PATH=/src/swoogo_autodeploy_resources/swoogo_autodeploy_resources -e PROJECT_ID=${{ vars.PROJECT_ID }} -e PRIVATE_KEY_ID=${{ vars.PRIVATE_KEY_ID }} -e PRIVATE_KEY=${{ vars.PRIVATE_KEY }} -e CLIENT_EMAIL=${{ vars.CLIENT_EMAIL }} -e CLIENT_ID=${{ vars.CLIENT_ID }} ghcr.io/joaquin-gamba/swoogo-autodeploy-resources/swoogo_autodeploy_resources:0.1.0
